name: Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm install      
    - run: npm run coverage